config/routes.rb
Bookstore::Application.routes.draw do

  
  resources :comments

  resources :category_items

  resources :books

  resources :categories
  controller :categories do
    get 'category/up/:id' => 'categories#up', as: 'category_up'
    get 'category/down/:id' => 'categories#down', as: 'category_down'
    get 'category/display_books/:id' => 'categories#display_books', as: 'category_display_books' 
    get 'category/display_other_books/:id' => 'categories#display_other_books', as: 'category_display_other_books' 
    get 'category/add_book/:category_id/:book_id' => 'categories#add_book', as: 'category_add_book' 
    get 'category/remove_book/:category_id/:book_id' => 'categories#remove_book', as: 'category_remove_book'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  controller :users do
    get 'activate/:token' => 'users#activate', as: 'activate'
    get 'user/upgrade/:id' => 'users#upgrade', as: 'upgrade'
    get 'user/downgrade/:id' => 'users#downgrade', as: 'downgrade'
    get 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    post 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    get 'user/password_reset_result/:token' => 'users#password_reset_result', as: 'reset_result'
    post 'user/password_reset_result' => 'users#password_reset_result', as: 'password_reset_result'
    get 'user/change_email' => 'users#change_email', as: 'change_email_address'
    post 'user/change_email' => 'users#change_email', as: 'change_email'
    get 'user/change_password' => 'users#change_password', as: 'change_password'
    post 'user/change_password' => 'users#change_password', as: 'change_password'
  end
  
  controller :store do
    get 'store/index' => 'store#index', as: 'store'
    get 'store/index/:category' => 'store#index', as: 'store_browse'    
    get 'store/index/:category/:pagination' => 'store#index', as: 'store_browse_pag'    
    get 'store/search' => 'store#book_search', as: 'book_search'    
    get 'store/:pagination/search' => 'store#book_search', as: 'book_search_pagination' 
    get 'store/change_pagination/:number' => 'store#change_pagination', as: 'store_change_pagination'   
  end

  root to: 'store#index', as: 'store'

end

app/models/user.rb
require 'gmail'

class User < ActiveRecord::Base
  attr_accessible :username, :role, :activation, :account_creation_date, :birthday, :email_address, :full_name, :password_digest, :phone, :password, :password_confirmation, :tokenized_code
  validates :email_address, :full_name, :username, :phone, :presence => true
  validates :username, :uniqueness => true
  validates :email_address, :format => {
    with: %r{\w+@\w+\.com$}i,
    message: 'must be in format xxx@xxx.com'
  }
  validates :phone, :format => {
    with: %r{0[0-9][0-9][0-9][0-9][0-9][0-9][0-9]+}i,
    message: 'must be in format 0xxxxxxxx (all digits)'
  }
  
  has_many :comments, :dependent => :destroy

  has_secure_password
  after_destroy :ensure_an_admin_remains
  after_save :ensure_an_admin_remains
  before_create :set_defaults

  def add_token
    self.update_attribute("tokenized_code", Digest::MD5.hexdigest("#{self.full_name} #{self.email_address}\
      #{rand(1000).to_s} #{rand(1000).to_s} #{rand(1000).to_s}"))
  end
  
  def send_activation_email(name, account, email_address, activate_link)
    send_email(email_address, 
      "Max's Online Bookstore Account Activation",
      "Welcome to Max's Online Bookstore, #{name}. <br /> 
      Please copy the following link and paste them to the browser address bar to activate your account: <br />
      #{activate_link}",
      "<p>Welcome to Max's Online Bookstore, #{name}.</p>
        <p>You have recently registered account #{account}</p>
        <p>Please click the following link to activate your account: </p>
        <a href='#{activate_link}'> Activate Account </a>"
      )
  end

  def send_password_reset_email(reset_link)
    send_email(self.email_address, 
      "Max's Online Bookstore Password Reset",
      "Welcome to Max's Online Bookstore, #{self.full_name}. <br /> 
      Please copy the following link and paste them to the browser address bar to reset your password: <br />
      #{reset_link}",
      "<p>Welcome to Max's Online Bookstore, #{self.full_name}.</p>
        <p>You have recently requested to reset your password of account #{self.username}</p>
        <p>Please click the following link to reset your password: </p>
        <a href='#{reset_link}'> Reset Password </a>"
      )
  end

  def send_email(email_address, subj, text, html)
    unless Rails.env.test?
      gmail = Gmail.new("ngoc.nguyen@stanyangroup.com", "hongngoc92")
      gmail.deliver do
        to email_address 
        subject subj
        text_part do
          body text
        end
        html_part do
          body html
        end
      end
    end
  end
  
  def change_password(new_password)
    self.update_attribute("password", new_password)
    self.update_attribute("password_confirmation", new_password)
  end

  private
  
  def set_defaults    
    self.account_creation_date = Date.current
    self.role ||= "normal"
    self.activation ||= false
    self.tokenized_code = Digest::MD5.hexdigest("#{self.full_name} #{self.email_address} #{rand(1000).to_s} #{rand(1000).to_s} #{rand(1000).to_s}")  
  end

  def ensure_an_admin_remains
    if User.find_by_role("admin").nil?
      raise "Can't delete/downgrade the last admin"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 # skip_before_filter :user_authorize, :admin_authorize
  
  skip_before_filter :user_authorize, :only => [:password_reset, :password_reset_result, :activate, :create, :new]
  skip_before_filter :admin_authorize, :only => [:password_reset, :password_reset_result, :activate, :create, :new, :change_email, :change_password, :update, :edit]
  include SimpleCaptcha::ControllerHelpers

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def activate
    @code = params[:token]
    @user = User.find_by_tokenized_code(@code)
    if @user
      @user.update_attribute("activation", true)
      @user.update_attribute("tokenized_code", "")
      session[:role] = @user.role
      session[:user_id] = @user.id 
      flash[:notice] = "Activation completed."
    end

    respond_to do |format|
      format.html 
      format.json { render :json => @user, :status => :created, :location => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    if session[:role] != "admin" && params[:id] != session[:user_id].to_s
      redirect_to store_url, :notice => "Access restricted."
    else
      @user = User.find(params[:id])
    end
  end

  # POST /users
  # POST /users.json
  def create
    if simple_captcha_valid?
      @user = User.new(params[:user]) 
      respond_to do |format|
        if @user.save
          @user.send_activation_email(@user.full_name, @user.username, @user.email_address, activate_url(@user.tokenized_code))
          format.html { redirect_to login_url, :notice => "Registration completed. Please check your email to activate the account." }
          format.json { render :json => @user, :status => :created, :location => @user }
        else
          format.html { render :action => "new" }
          format.json { render :json => @user.errors, :status => :unprocessable_entity }
        end
      end
    else    
      redirect_to new_user_url, :notice => "The letters you entered do not match the image."
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if session[:role] != "admin" && params[:id] != session[:user_id].to_s
      redirect_to store_url, :notice => "Access restricted."
    else
    if simple_captcha_valid?
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to store_url, :notice => "User's information was successfully updated." }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @user.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to edit_user_url(@user), :notice => "The letters you entered do not match the image."
    end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
    rescue Exception => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def upgrade
    @user = User.find(params[:id])
    respond_to do |format|
      if !@user.activation    
        format.html { redirect_to users_url, :notice => "User that is not activated cannot become admin." }
        format.json { head :no_content }      
      elsif @user.update_attribute("role", "admin")
        format.html { redirect_to users_url, :notice => "User was successfully upgraded to admin." }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :notice => :unprocessable_entity }
      end
    end
  end

  def downgrade
    user = User.find(params[:id])
    respond_to do |format|
      begin
        if user.update_attribute("role", "normal")
          format.html { redirect_to users_url, :notice => "User was successfully downgraded to normal." }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => user.errors, :status => :unprocessable_entity }
        end
      rescue Exception => e
        flash[:notice] = e.message
        format.html { redirect_to users_url }
      end
    end
  end

  def password_reset_result
    if (request.get?)
      @code = params[:token]
      @user = User.find_by_tokenized_code(@code)
      if @user and @user.activation
        session[:code] = @code
        session[:temp_username] = @user.username
        flash[:notice] = "Correct token code."
      else        
        flash[:notice] = "Incorrect token code."
      end
    else
      @user_info = User.new(params[:user])
      respond_to do |format|
        if @user_info.password != @user_info.password_confirmation
          format.html { redirect_to reset_result_path(session[:code]), :notice => "Password confirmation does not match the password." }    
        else          
          @user = User.find_by_username(session[:temp_username])
          @user.change_password(@user_info.password)
          @user.update_attribute("tokenized_code", "")
          session[:code] = nil
          session[:temp_username] = nil    
          session[:role] = @user.role
          session[:user_id] = @user.id 
          format.html { redirect_to users_url, :notice => "New password has been set." }
        end
      end
    end
  end

  def password_reset
    if (request.post?)
      if simple_captcha_valid?
        @user_info = User.new(params[:user])
        @user = User.find_by_username(@user_info.username)
        respond_to do |format|
          if !@user or @user.email_address != @user_info.email_address
            format.html { redirect_to password_reset_url, :notice => "Incorrect username/email address combination." }
          elsif !@user.activation
            format.html { redirect_to password_reset_url, :notice => "This account is not activated." }          
          else
            @user.add_token
            @user.send_password_reset_email(reset_result_url(@user.tokenized_code))
            format.html { redirect_to password_reset_url, :notice => "Please check your email to reset the password." }
          end
        end
      else
        redirect_to password_reset_url, :notice => "The letters you entered does not match the image."
      end
    else
      @user = User.new
    end
  end
  
  def change_email    
    if (request.post?)
      @user_info = User.new(params[:user])
      @user = User.find(session[:user_id])
      if @user.authenticate(@user_info.password)
        @user_info.valid?
        if @user_info.errors.include?(:email_address)
          redirect_to change_email_address_url, :notice => "Invalid new email address."
        else
          @user.update_attribute("email_address", @user_info.email_address)
          redirect_to store_url, :notice => "Email address is changed successfully."
        end
      else
        redirect_to change_email_address_url, :notice => "Incorrect password."
      end
    end
    @user = User.new
  end
  
  def change_password  
    if (request.post?)
      @user = User.find(session[:user_id])
      if @user.authenticate(params[:old_password])
        @user.password = params[:new_password]
        @user.password_confirmation = params[:confirm_password]
        if @user.valid?
          @user.change_password(params[:new_password])
          redirect_to store_url, :notice => "Password is change successfully."
        else          
          redirect_to change_password_url, :notice => "New password and its confirmation do not match."
        end
      else
        redirect_to change_password_url, :notice => "Incorrect password."
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>. Invalid registration.</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select(:birthday, :start_year => 1920, :end_year => 2000) %>
  </div>
  <br />
  <%= show_simple_captcha %> <br />
  <div class="actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

app/views/users/change_email.html.erb
<h1> Please enter the following information to change your email </h1> <br />
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= form_for(@user, :url => change_email_path, :method => :post) do |f| %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Change", :class => "btn btn-info" %>
  </div>
<% end %>

app/views/users/change_email.html.haml
%h1
  Please enter the following information to change your email
%br
- if notice
  %p{ :id => "notice" } 
    = notice
    
= form_for(@user, :url => change_email_path, :method => :post) do |f|
  .field
    = f.label :password 
    = f.password_field :password 
  .field
    = f.label :email_address 
    = f.text_field :email_address
  %br
  .actions
    = f.submit "Change", :class => "btn btn-info"

app/views/users/change_password.html.erb
<h1> Please enter the following information to change your password </h1> <br />
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

  <%= form_tag do %>
    <fieldset>
      <legend>Change Password</legend>

      <div>
        <%= label_tag 'Old password:' %>
        <%= password_field_tag :old_password, params[:old_password] %>
      </div>
      <div>
        <%= label_tag :new_password, 'New password:' %>
        <%= password_field_tag :new_password, params[:new_password] %>
      </div>
      <div>
        <%= label_tag :confirm_password, 'New password confirmation:' %>
        <%= password_field_tag :confirm_password, params[:confirm_password] %>
      </div>         
      <div>
        <%= submit_tag "Change", :class => "btn btn-info" %>
      </div>
    </fieldset>
  <% end %>

app/views/users/edit.html.erb
<h1>Change Personal Information</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>. Invalid registration.</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_select(:birthday, :start_year => 1920, :end_year => 2000) %>
  </div>
  <br />
  <%= show_simple_captcha %> <br />
  <div class="actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

<%= link_to "Back", users_path %>

app/views/users/index.html.erb
<h1>User List</h1>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<table width="100%">
  <tr class="user">
    <th>Email address</th>
    <th>Username</th>
    <th>Phone</th>
    <th>Full name</th>
    <th>Birthday</th>
    <th>Account creation date</th>
    <th colspan="2">Activation</th>
    <th colspan="2">Role</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr class="user">
    <td><%= user.email_address %></td>
    <td><%= user.username %></td>
    <td><%= user.phone %></td>
    <td><%= user.full_name %></td>
    <td><%= user.birthday %></td>
    <td><%= user.account_creation_date %></td>
    <td><%= user.activation %></td>
    <td>
        <% if !user.activation && !user.tokenized_code.empty? %>
            <%= link_to "Activate", activate_path(user.tokenized_code) %>
        <% end %>
    </td>
    <td><%= user.role %></td>
    <td>
        <% if user.role == "admin" %>
            <%= link_to image_tag("arrow_down.jpg"), downgrade_path(user.id.to_s) %>
        <% else %>
            <%= link_to image_tag("arrow_up.jpeg"), upgrade_path(user.id.to_s) %>   
        <% end %>
    </td>
    <td><%= link_to "Edit", edit_user_url(user) %></td>
    <td><%= link_to "Delete", user, :method => :delete, :data => { :confirm => "Are you sure?" } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/index.html.haml
%h1
  User List
- if notice
  %p{ :id => "notice" } 
    = notice
    
%table{ :width => "100%" }
  %tr{ :class => "user" }
    %th Email address     
    %th Username
    %th Phone
    %th Full name
    %th Birthday
    %th Account creation date
    %th{ :colspan => "2" } Activation
    %th{ :colspan => "2" } Role
    %th
    %th

  - @users.each do |user|
    %tr{ :class => "user" }
      %td 
        = user.email_address
      %td 
        = user.username
      %td 
        = user.phone 
      %td 
        = user.full_name 
      %td 
        = user.birthday 
      %td 
        = user.account_creation_date
      %td 
        = user.activation 
      %td
        - if !user.activation && !user.tokenized_code.empty? 
          = link_to "Activate", activate_path(user.tokenized_code) 
      %td
        = user.role
      %td
        - if user.role == "admin"
          = link_to image_tag("arrow_down.jpg"), downgrade_path(user.id.to_s)
        - else 
          = link_to image_tag("arrow_up.jpeg"), upgrade_path(user.id.to_s) 
      %td
        = link_to "Edit", edit_user_url(user)
      %td
        = link_to "Delete", user, :method => :delete, :data => { :confirm => "Are you sure?" }

app/views/users/new.html.erb
<h1>Registration</h1>

<%= render "form" %>

app/views/users/new.html.haml
%h1
  Registration
= render "form"

app/views/users/password_reset.html.erb
<h1> Please enter the following information to reset your password </h1> <br />
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= form_for(@user, :url => {:action => "password_reset"}, :method => :post) do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <br />
  <%= show_simple_captcha %> <br />
  <div class="actions">
    <%= f.submit "Reset", :class => "btn btn-info" %>
  </div>
<% end %>

app/views/users/password_reset.html.haml
%h1 Please enter the following information to reset your password
%br
- if notice
  %p{ :id => "notice" } 
    = notice

= form_for(@user, :url => {:action => "password_reset"}, :method => :post) do |f|
  .field
    = f.label :username 
    = f.text_field :username 
  .field
    = f.label :email_address 
    = f.text_field :email_address  
  %br
  = show_simple_captcha
  %br
  .actions
    = f.submit "Reset", :class => "btn btn-info" 

app/views/users/password_reset_result.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<% if @user %>
Account <%= @user.username %>'s password
has been resetted with code <%= @code %>

<%= form_for(@user, :url => password_reset_result_path, :method => :post) do |f| %>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Reset password", :class => "btn btn-info" %>
  </div>
<% end %>
<% end %>

app/views/users/password_reset_result.html.haml
- if notice
  %p{ :id => "notice" } 
    = notice

- if @user 
  Account 
  = @user.username 
  's password is being reset with code 
  = @code
  = form_for(@user, :url => password_reset_result_path, :method => :post) do |f|
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    .actions
      = f.submit "Reset password", :class => "btn btn-info"

app/views/users/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<% if @user %>
Account <%= @user.username %>
has been activated with code <%= @code %>
<% else %>
Fake token <%= @code %>
<% end %>