config/routes.rb
Bookstore::Application.routes.draw do

  
  resources :comments

  resources :category_items

  resources :books

  resources :categories
  controller :categories do
    get 'category/up/:id' => 'categories#up', as: 'category_up'
    get 'category/down/:id' => 'categories#down', as: 'category_down'
    get 'category/display_books/:id' => 'categories#display_books', as: 'category_display_books' 
    get 'category/display_other_books/:id' => 'categories#display_other_books', as: 'category_display_other_books' 
    get 'category/add_book/:category_id/:book_id' => 'categories#add_book', as: 'category_add_book' 
    get 'category/remove_book/:category_id/:book_id' => 'categories#remove_book', as: 'category_remove_book'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  controller :users do
    get 'activate/:token' => 'users#activate', as: 'activate'
    get 'user/upgrade/:id' => 'users#upgrade', as: 'upgrade'
    get 'user/downgrade/:id' => 'users#downgrade', as: 'downgrade'
    get 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    post 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    get 'user/password_reset_result/:token' => 'users#password_reset_result', as: 'reset_result'
    post 'user/password_reset_result' => 'users#password_reset_result', as: 'password_reset_result'
    get 'user/change_email' => 'users#change_email', as: 'change_email_address'
    post 'user/change_email' => 'users#change_email', as: 'change_email'
    get 'user/change_password' => 'users#change_password', as: 'change_password'
    post 'user/change_password' => 'users#change_password', as: 'change_password'
  end
  
  controller :store do
    get 'store/index' => 'store#index', as: 'store'
    get 'store/index/:category' => 'store#index', as: 'store_browse'    
    get 'store/index/:category/:pagination' => 'store#index', as: 'store_browse_pag'    
    get 'store/search' => 'store#book_search', as: 'book_search'    
    get 'store/:pagination/search' => 'store#book_search', as: 'book_search_pagination' 
    get 'store/change_pagination/:number' => 'store#change_pagination', as: 'store_change_pagination'   
  end

  root to: 'store#index', as: 'store'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author_name, :description, :photo_url, :published_date, :publisher_name, :title, :total_rating_count, :total_rating_value, :unit_price

  validates :author_name, :description, :photo_url, :published_date, :publisher_name, :title, :unit_price, :presence => true
  
  before_destroy :ensure_not_referenced_by_any_category_item
  before_create :set_defaults
  has_many :category_items
  has_many :categories, :through => :category_items
  has_many :comments, :dependent => :destroy
  
  def add_rate(rate)
    self.update_attribute("total_rating_count", total_rating_count + 1)
    self.update_attribute("total_rating_value", total_rating_value + rate)
  end
  
  def remove_rate(rate)
    self.update_attribute("total_rating_count", total_rating_count - 1 < 0 ? 0 : total_rating_count - 1)
    self.update_attribute("total_rating_value", total_rating_value - rate < 0 ? 0 : total_rating_value - rate)
  end
  
  def add_comment(comment, user_id, book_id)
    if !Comment.where("user_id = ? and book_id = ?", user_id, book_id).empty?
      "You cannot comment and rate a book twice."
    else
      comment.user_id = user_id
      comment.book_id = book_id
      comment.date = Date.current
      if comment.save
        add_rate(comment.rating)
        "Comment has been made successfully."
      else
        comment.errors.full_messages[0]
      end
    end
  end
  
  private
  # ensure that there are no category items referencing this book
  def ensure_not_referenced_by_any_category_item
    if category_items.empty?
      return true
    else
      errors.add(:base, "Please remove the book from category first.")
      return false
    end
  end
  
  def set_defaults
    self.total_rating_value = 0
    self.total_rating_count = 0
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_filter :admin_authorize, :user_authorize, :only => [:show]
  
  # GET /books
  # GET /books.json
  def index
    @books = Book.paginate page: params[:page], per_page: 10

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @average_rating = @book.total_rating_count == 0 ? 0 : @book.total_rating_value / @book.total_rating_count
    @rating = @average_rating.round
    if session[:user_id]
      @comment = Comment.new
      session[:book_id] = @book.id
    end
    @comments = @book.comments.order(:date).paginate page: params[:page], per_page: 5

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_url, :notice => "Book was successfully created." }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.json { render :json => @books.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, :notice => "Book was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @books.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      if @book.errors.any?
        format.html { redirect_to books_url, :notice => @book.errors.full_messages[0] }
      else
        format.html { redirect_to books_url, :notice => "Book was removed successfully." }
      end
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "better_field" %>
  </div>
  <div class="field">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :publisher_name %>
    <%= f.text_field :publisher_name %>
  </div>
  <div class="field">
    <%= f.label :published_date %>
    <%= f.date_select(:published_date, :start_year => 1800, :end_year => 2013) %>
  </div>
  <div class="field">
    <%= f.label :unit_price %>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_form.html.haml
= form_for(@book) do |f| 
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li
            = msg

  .field
    = f.label :title 
    = f.text_field :title 
  .field
    = f.label :description 
    = f.text_area :description, :class => "better_field" 
  .field
    = f.label :author_name 
    = f.text_field :author_name 
  .field
    = f.label :publisher_name 
    = f.text_field :publisher_name 
  .field
    = f.label :published_date 
    = f.date_select(:published_date, :start_year => 1800, :end_year => 2013) 
  .field
    = f.label :unit_price 
    = f.text_field :unit_price 
  .field
    = f.label :photo_url 
    = f.text_field :photo_url 
  .actions
    = f.submit 

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Detail', @book 
|
= link_to 'Back', books_path 

app/views/books/index.html.erb
<h1>Book List</h1>

  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
<table>

<%= link_to '+ New Book', new_book_path %>
<% @books.each do |book| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= image_tag(book.photo_url, :class => 'list_image') %></td>
    <td>      
      <% @rating = (book.total_rating_count == 0 ? 0 : book.total_rating_value / book.total_rating_count).round %>
      <div class="left"><%= render 'comments/stars' %></div><br />
      <p>by <%= book.author_name %></p>
    </td>
    <td class="list_description">  
      <dl>
        <dt><%= book.title %></dt>
        <dd><%= truncate(strip_tags(book.description), length: 80) %></dd>
      </dl>
    </td>
    <td class="list_actions">
      <%= link_to 'Show', book %><br/>
      <%= link_to 'Edit', edit_book_url(book) %><br/>
      <%= link_to 'Delete', book, confirm: 'Are you sure?', method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<p> <%= will_paginate @books %> </p>

app/views/books/index.html.haml
- if notice
  %p{ :id => "notice" }
    = notice 
    
%h1 Book List 
%table
  = link_to '+ New Book', new_book_path
  - @books.each do |book|
    %tr{ :class => cycle('list_line_odd', 'list_line_even') }
      %td
        = image_tag(book.photo_url, :class => 'list_image')
      %td      
        - @rating = (book.total_rating_count == 0 ? 0 : book.total_rating_value / book.total_rating_count).round
        .left
          = render 'comments/stars'
          %br
        %p 
          by 
          = book.author_name
      %td{ :class => "list_description" } 
        %dl
          %dt
            = book.title
          %dd
            = truncate(strip_tags(book.description), length: 80)
      %td{ :class => "list_actions" }
        = link_to 'Show', book
        %br
        = link_to 'Edit', edit_book_url(book)
        %br
        = link_to 'Delete', book, confirm: 'Are you sure?', method: :delete 

%br
%p
  = will_paginate @books

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/new.html.haml
%h1 New book
= render 'form'
= link_to 'Back', books_path

app/views/books/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1><%= @book.title %></h1>

<%= image_tag(@book.photo_url, :class => 'detail_image') %>
by <b><%= @book.author_name %></b> <br />
<%= render 'comments/stars' %>
<div class="left">Average Rating: <%= number_with_precision(@average_rating, precision: 2) %></div>   
<p>| Rating count: <%= number_with_precision(@book.total_rating_count, precision: 0)%></p>
<p>
  <%= strip_tags(@book.description) %>
</p>

<p>
  <b>Publisher: </b>
  <%= @book.publisher_name %>
</p>

<p>
  <b>Published date:</b>
  <%= @book.published_date %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@book.unit_price) %>
</p>

<%= link_to 'Back', store_path %>
<h3>Comments</h3>

<% @comments.each do |comment| %>
  <div class="comment">
    <div>
      <% if session[:role] == "admin" %>
        <div class="right">          
          <%= link_to 'Delete comment', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
      User <b><%=comment.user.username%></b> rated 
      <% @rating = comment.rating %>
      <%= render 'comments/stars' %>
      on <%= comment.date %>
    </div>
    <b>His/her comment: </b> <br />
    <%= comment.content %>
  </div>
<% end %>
<p> <%= will_paginate @comments %> </p>

<% if @comment %>
<div class="comment">
  <%= form_for(@comment) do |f| %>
    <div class="field">
      <div class="left">
      <%= f.label "Your comment: "%><br />
      <%= f.label "Rating" %>
      <%= f.select :rating, %w[1 2 3 4 5] %>
      <%= f.hidden_field :book_id, :value => @book.id %>
    </div>
      <%= f.text_area :content, :class => "better_field" %>
    </div>
    
    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-info" %>
    </div>
  <% end %>  
</div>
<% end %>

app/views/books/show.html.haml
- if notice
  %p{ :id => "notice" }
    = notice
%h1
  = @book.title

= image_tag(@book.photo_url, :class => 'detail_image')
by 
%b
  = @book.author_name
%br
= render 'comments/stars'
.left
  Average Rating:
  = number_with_precision(@average_rating, precision: 2)
%p
  | Rating count: 
  = number_with_precision(@book.total_rating_count, precision: 0)
%p
  = strip_tags(@book.description) 
%p
  %b Publisher:
  = @book.publisher_name
%p
  %b Published date:
  = @book.published_date 
%p
  %b Price:
  = number_to_currency(@book.unit_price)
= link_to 'Back', store_path

%h3 Comments
- @comments.each do |comment| 
  .comment
    .field
      - if session[:role] == "admin"
        .right          
          = link_to 'Delete comment', comment, method: :delete, data: { confirm: 'Are you sure?' }
      User 
      %b
        =comment.user.username
      rated 
      - @rating = comment.rating
      = render 'comments/stars'
      on 
      = comment.date
    %b His/her comment:
    %br
    = comment.content 
%p
  = will_paginate @comments

- if @comment
  .comment
    = form_for(@comment) do |f|
      .field
        .left
          = f.label "Your comment: "
          %br
          = f.label "Rating"
          = f.select :rating, %w[1 2 3 4 5]
        = f.text_area :content, :class => "better_field"    
      .actions
        = f.submit "Submit", :class => "btn btn-info"