config/routes.rb
Bookstore::Application.routes.draw do

  
  resources :comments

  resources :category_items

  resources :books

  resources :categories
  controller :categories do
    get 'category/up/:id' => 'categories#up', as: 'category_up'
    get 'category/down/:id' => 'categories#down', as: 'category_down'
    get 'category/display_books/:id' => 'categories#display_books', as: 'category_display_books' 
    get 'category/display_other_books/:id' => 'categories#display_other_books', as: 'category_display_other_books' 
    get 'category/add_book/:category_id/:book_id' => 'categories#add_book', as: 'category_add_book' 
    get 'category/remove_book/:category_id/:book_id' => 'categories#remove_book', as: 'category_remove_book'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  controller :users do
    get 'activate/:token' => 'users#activate', as: 'activate'
    get 'user/upgrade/:id' => 'users#upgrade', as: 'upgrade'
    get 'user/downgrade/:id' => 'users#downgrade', as: 'downgrade'
    get 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    post 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    get 'user/password_reset_result/:token' => 'users#password_reset_result', as: 'reset_result'
    post 'user/password_reset_result' => 'users#password_reset_result', as: 'password_reset_result'
    get 'user/change_email' => 'users#change_email', as: 'change_email_address'
    post 'user/change_email' => 'users#change_email', as: 'change_email'
    get 'user/change_password' => 'users#change_password', as: 'change_password'
    post 'user/change_password' => 'users#change_password', as: 'change_password'
  end
  
  controller :store do
    get 'store/index' => 'store#index', as: 'store'
    get 'store/index/:category' => 'store#index', as: 'store_browse'    
    get 'store/index/:category/:pagination' => 'store#index', as: 'store_browse_pag'    
    get 'store/search' => 'store#book_search', as: 'book_search'    
    get 'store/:pagination/search' => 'store#book_search', as: 'book_search_pagination' 
    get 'store/change_pagination/:number' => 'store#change_pagination', as: 'store_change_pagination'   
  end

  root to: 'store#index', as: 'store'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :sort_order
  
  validates :name, :uniqueness => true
  validates :name, :presence => true
  
  has_many :category_items, :dependent => :destroy
  has_many :books, through: :category_items
  
  before_create :set_sort_order
  
  default_scope order('sort_order')
  
  def add_book(book_id)
    item = category_items.build(:book_id => book_id)
    item
  end
  
  def self.sort_order_change(category_id, direction)
    category = Category.find(category_id)
    if direction == "up"
      if category.sort_order == 1
        "Category is already the first."
      else
        other_category = Category.find_by_sort_order(category.sort_order - 1)
        category.update_attribute("sort_order", category.sort_order - 1)  
        if !other_category.nil?
          other_category.update_attribute("sort_order", category.sort_order + 1)
        end
        "Sort order of #{category.name} is up by 1."
      end  
    else
      if category.sort_order == Category.maximum(:sort_order)
        "Category is already the last."
      else
        other_category = Category.find_by_sort_order(category.sort_order + 1)
        category.update_attribute("sort_order", category.sort_order + 1)  
        if !other_category.nil?
          other_category.update_attribute("sort_order", category.sort_order - 1)
        end
        "Sort order of #{category.name} is down by 1."
      end  
    end
  end
  
  private
  def set_sort_order
    self.sort_order = Category.maximum(:sort_order) ? Category.maximum(:sort_order) + 1 : 1
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:sort_order)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, :notice => "Category was successfully created." }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to categories_url, :notice => "Category was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, :notice => "Category was successfully removed." }
      format.json { head :no_content }
    end
  end
  
  def up
    result = Category.sort_order_change(params[:id], "up")
    redirect_to categories_url, notice: result
  end
  
  def down
    result = Category.sort_order_change(params[:id], "down")
    redirect_to categories_url, :notice => result
  end
  
  def display_books
    @category = Category.find(params[:id])
    @books = @category.books.paginate page: params[:page], per_page: 6
  end
  
  def display_other_books
    @category = Category.find(params[:id])
    if @category.books.empty?
      @other_books = Book.paginate page: params[:page], per_page: 6
    else
      @other_books = Book.where('id not in (?)', @category.books).paginate page: params[:page], per_page: 6
    end
  end
  
  def add_book
    category = Category.find(params[:category_id])
    book = Book.find(params[:book_id])
    item = category.add_book(book.id)
    
    respond_to do |format|
      if item.save
        format.html { redirect_to category_display_other_books_url(category.id), :notice => "Book added to category successfully." }
        format.json { render :json => item, :status => :created, :location => item }
      else
        format.html { render action: "new" }
        format.json { render :json => item.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def remove_book
    category = Category.find(params[:category_id])
    book = Book.find(params[:book_id])
    CategoryItem.where('category_id = (?) and book_id = (?)', category.id, book.id).first.destroy 
    
    respond_to do |format|
      format.html { redirect_to category_display_books_url(category.id), :notice => "Book removed from category successfully." }
      format.json { render :json => item, :status => :created, :location => item }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> :</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any? 
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        \:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li
            = msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit :class => "btn btn-info" 

app/views/categories/book_display.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<div class="container-fluid fill">
    <div class="row-fluid">
      <h1>Category <%= @category.name %></h1>
      <p>The books that belong to this category is in the right panel.</p>
        <div class="span5 hero-unit filler">
          Add book to this category by clicking + <br />
          <% @other_books.each do |book| %>
          <div class="list">
            <%= link_to('+', category_book_add_url(@category.id, book.id), class: "btn btn-info") %>
            <%= image_tag(book.photo_url, class: "list_image") %>
            <p class="list_text"><%= book.title %></p>
          </div>
          <% end %>
        </div>
        <div class="span5 hero-unit filler">
          Remove book from this category by clicking -<br />          
          <% @category_books.each do |book| %>
          <div class="list">
            <%= link_to('-', category_book_remove_url(@category.id, book.id), class: "btn btn-info") %>
            <%= image_tag(book.photo_url, class: "list_image") %>
            <p class="list_text"><%= book.title %></p>
          </div>
          <% end %>
        </div>
    </div>
</div>

<%= link_to 'Back', categories_path %>

app/views/categories/display_books.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Category <%= @category.name %></h1>
These books are currently in the category <br />
Remove them from this category by clicking - <br />
<div class="container">
  <% @books.each do |book| %>
    <div class="list">
      <%= link_to('-', category_remove_book_url(@category.id, book.id), class: "btn btn-info") %>
      <%= image_tag(book.photo_url, :class => "list_image") %>
      <p class="list_text"><%= book.title %></p>
    </div>
  <% end %>
</div>
<p> <%= will_paginate @books %> </p>

<%= link_to 'Back', categories_path %>

app/views/categories/display_books.html.haml
- if notice
  %p{ :id => "notice" }
    = notice

%h1 
  Category 
  = @category.name
These books are currently in the category 
%br
Remove them from this category by clicking -
%br
.container
  - @books.each do |book|
    .list
      = link_to('-', category_remove_book_url(@category.id, book.id), class: "btn btn-info") 
      = image_tag(book.photo_url, :class => "list_image")
      %p{ :class => "list_text" }
        = book.title 
%p
  = will_paginate @books

= link_to 'Back', categories_path

app/views/categories/display_other_books.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Category <%= @category.name %></h1>
These books are not in the category <br />
Add them to this category by clicking + <br />
<div class="container">
  <% @other_books.each do |book| %>
    <div class="list">
      <%= link_to('+', category_add_book_url(@category.id, book.id), class: "btn btn-info") %>
      <%= image_tag(book.photo_url, :class => "list_image") %>
      <p class="list_text"><%= book.title %></p>
    </div>
  <% end %>
</div>
<p> <%= will_paginate @other_books %> </p>

<%= link_to 'Back', categories_path %>

app/views/categories/display_other_books.html.haml
- if notice
  %p{ :id => "notice" }
    = notice

%h1
  Category
  = @category.name
These books are not in the category
%br
Add them to this category by clicking +
%br
.container
  - @other_books.each do |book|
    .list
      = link_to('+', category_add_book_url(@category.id, book.id), class: "btn btn-info")
      = image_tag(book.photo_url, :class => "list_image")
      %p{ :class => "list_text" }
        = book.title
%p
  = will_paginate @other_books

= link_to 'Back', categories_path

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Category List</h1>

<table width="100%">
  <tr class="category">
    <th>Name</th>
    <th colspan="3">Sort order</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr class="category">
    <td><%= category.name %></td>
    <td><%= number_with_precision(category.sort_order, precision: 0) %></td>
    <td>
            <%= link_to image_tag("arrow_down.jpg"), category_down_path(category.id) %>
    </td>
    <td>
            <%= link_to image_tag("arrow_up.jpeg"), category_up_path(category.id) %>   
    </td>
    <td><%= link_to 'Add book', category_display_other_books_path(category) %></td>
    <td><%= link_to 'Remove book', category_display_books_path(category) %></td>
    <td><%= link_to 'Change Name', edit_category_path(category) %></td>
    <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/index.html.haml
- if notice
  %p{ :id => "notice" }
    = notice

%h1 Category List
%table{ :width => "100%" }
  %tr{ :class => "category" }
    %th Name
    %th{ :colspan => "3" } Sort order
    %th
    %th
    %th
    %th

  - @categories.each do |category| 
    %tr{ :class => "category" }
      %td
        = category.name
      %td
        = number_with_precision(category.sort_order, precision: 0)
      %td
        = link_to image_tag("arrow_down.jpg"), category_down_path(category.id) 
      %td
        = link_to image_tag("arrow_up.jpeg"), category_up_path(category.id)
      %td
        = link_to 'Add book', category_display_other_books_path(category) 
      %td
        = link_to 'Remove book', category_display_books_path(category) 
      %td
        = link_to 'Change Name', edit_category_path(category) 
      %td
        = link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } 
%br
= link_to 'New Category', new_category_path 

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path 

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Sort order:</b>
  <%= @category.sort_order %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>