config/routes.rb
Bookstore::Application.routes.draw do

  
  resources :comments

  resources :category_items

  resources :books

  resources :categories
  controller :categories do
    get 'category/up/:id' => 'categories#up', as: 'category_up'
    get 'category/down/:id' => 'categories#down', as: 'category_down'
    get 'category/display_books/:id' => 'categories#display_books', as: 'category_display_books' 
    get 'category/display_other_books/:id' => 'categories#display_other_books', as: 'category_display_other_books' 
    get 'category/add_book/:category_id/:book_id' => 'categories#add_book', as: 'category_add_book' 
    get 'category/remove_book/:category_id/:book_id' => 'categories#remove_book', as: 'category_remove_book'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  controller :users do
    get 'activate/:token' => 'users#activate', as: 'activate'
    get 'user/upgrade/:id' => 'users#upgrade', as: 'upgrade'
    get 'user/downgrade/:id' => 'users#downgrade', as: 'downgrade'
    get 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    post 'user/password_reset' => 'users#password_reset', as: 'password_reset'
    get 'user/password_reset_result/:token' => 'users#password_reset_result', as: 'reset_result'
    post 'user/password_reset_result' => 'users#password_reset_result', as: 'password_reset_result'
    get 'user/change_email' => 'users#change_email', as: 'change_email_address'
    post 'user/change_email' => 'users#change_email', as: 'change_email'
    get 'user/change_password' => 'users#change_password', as: 'change_password'
    post 'user/change_password' => 'users#change_password', as: 'change_password'
  end
  
  controller :store do
    get 'store/index' => 'store#index', as: 'store'
    get 'store/index/:category' => 'store#index', as: 'store_browse'    
    get 'store/index/:category/:pagination' => 'store#index', as: 'store_browse_pag'    
    get 'store/search' => 'store#book_search', as: 'book_search'    
    get 'store/:pagination/search' => 'store#book_search', as: 'book_search_pagination' 
    get 'store/change_pagination/:number' => 'store#change_pagination', as: 'store_change_pagination'   
  end

  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Max's Online Bookstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Max Bookshelf" %>
    <div id="time">
      <%= Time.now %>
    </div>
  </div>

  <div id="columns">
    <div id="side">
      <ul class="nav nav-pills nav-stacked" >
        <li><%= link_to raw("<i class='icon-home icon-white'></i> Home"), store_url %></li>
        <% if session[:role] %>
          <li><h3>User Panel</h3></li>        
          <li>
            <%= link_to raw("<i class='icon-edit icon-white'></i> Edit account information"), edit_user_url(session[:user_id]) %>
          </li>
          <li><%= link_to 'Change Email', change_email_address_url %></li>
          <li><%= link_to 'Change Password', change_password_path %></li>
          <li><%= link_to 'Log out', logout_url, method: :delete %></li>
          <% if session[:role] == "admin" %>
          <li><h3>Admin Panel</h3></li>      
          <li><%= link_to raw('User List'), users_url %></li>
          <li><%= link_to raw('Book List'), books_url %></li>
          <li><%= link_to raw('Category List'), categories_url %></li>
          <% end %>
        <% else %>
          <li><%= link_to 'Log In', login_url %></li>
          <li><%= link_to 'Register', new_user_url %></li>
          <li><%= link_to 'Forgot password?', password_reset_url %></li>
        <% end %>
      </ul>
      <h3 class="sidebar-title">Search</h3>
          <%= form_tag(book_search_url, :method => 'get', :class => "better-search-bar option") do |f| %>
          Search by:
          <div class="right">
            <div class="btn-group" data-toggle="buttons">
              <label>
                <input type="radio" name="search_type" id="pig" value="author"> Author Name
              </label>
              <label>
                <input type="radio" name="search_type" id="splunk" checked=true value="title"> Title
              </label>
            </div>    
          </div>
            <%= search_field_tag :search_input, "", class: "search-query span2" %>
            <button class='btn right'>
              <i class='icon-search'></i>
            </button>
            Choose a category: 
            <% @options = Category.all.map{|c| [c.name, c.id]} %>
            <% @options << ["All categories","all"] %>
            <%= select_tag :search_category, options_for_select(@options, "all") %>
          <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title Max's Online Bookstore
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body{ :class => controller.controller_name }
    #banner
      = image_tag("logo.png")
      = @page_title || "Max Bookshelf"
      #time
        = Time.now
    #columns
      #side
        %ul{ :class => "nav nav-pills nav-stacked" }
          %li
            = link_to raw("<i class='icon-home icon-white'></i> Home"), store_url
          - if session[:role]
            %li
              %h3 User Panel
            %li
              = link_to raw("<i class='icon-edit icon-white'></i> Edit account information"), |
              edit_user_url(session[:user_id]), :id => "edit"
            %li
              = link_to 'Change Email', change_email_address_url, :id => "change_email"
            %li
              = link_to 'Change Password', change_password_path, :id => "change_password"
            %li
              = link_to 'Log out', logout_url, method: :delete
            - if session[:role] == "admin"
              %li
                %h3 Admin Panel      
              %li
                = link_to raw('User List'), users_url, :id => "users"
              %li
                = link_to raw('Book List'), books_url, :id => "books"
              %li
                = link_to raw('Category List'), categories_url, :id => "categories"
          - else 
            %li
              = link_to 'Log In', login_url
            %li
              = link_to 'Register', new_user_url
            %li
              = link_to 'Forgot password?', password_reset_url
        %h3{ :class => "sidebar-title" } Search
        = form_tag(book_search_url, :method => 'get', :class => "better-search-bar option") do |f|
          .right
            .btn-group{ :toggle => "buttons" }
              %label
                %input{ :type => "radio", :name => "search_type", :id => "author", :value => "author" }>=' Author Name'
              %label
                %input{ :type => "radio", :name => "search_type", :id => "title", :value => "title", :checked => true }>=' Title'
          = search_field_tag :search_input, "", class: "search-query span2" 
          %button{ :class => 'btn right', :id => 'search' }
            %i{ :class => 'icon-search' }
          Choose a category: 
          - @options = Category.all.map{|c| [c.name, c.id]}
          - @options << ["All categories","all"]
          = select_tag :search_category, options_for_select(@options, "all")
      #main
        = yield